[frontend] Fix compilation of aarch64 m128 module (#632)
This PR fixes the compile error due to (unused) imports of missing modules
/ identifiers.

If I build the project in macOS on main, I get the following compile error:

```
error[E0432]: unresolved imports `crate::underlier::transpose_128b_values`, `crate::tower_levels`
  --> crates/field/src/arch/aarch64/m128.rs:28:2
   |
28 |     tower_levels::TowerLevel,
   |     ^^^^^^^^^^^^ could not find `tower_levels` in the crate root
...
31 |         impl_divisible, impl_iteration, transpose_128b_values, unpack_lo_128b_fallback,
   |                                         ^^^^^^^^^^^^^^^^^^^^^ no `transpose_128b_values` in `underlier`

For more information about this error, try `rustc --explain E0432`.
```

In PR #620 uses of tower_levels::TowerLevel and transpose_128b_values
were removed in both the aarch64 and x86_64 versions of m128 module.
However in the aarch64 version the imports remained (unused).

Then the aarch64 compilation broke after PR #621 removed the
tower_levels module completely but left the import in the aarch64 128
module.

I don't know why CI didn't catch this.

<https://github.com/IrreducibleOSS/monbijou/pull/620>
<https://github.com/IrreducibleOSS/monbijou/pull/621>